#!/bin/bash

CMD=$1
shift

case $CMD in
  r | run)
    (eval $(luarocks path --bin --tree lua_modules); "$@")
    ;;

  i | install)
    luarocks install --tree lua_modules "$@"
    ;;

  c | clean)
    luarocks purge --tree lua_modules
    ;;

  *)
    echo "Unknown command $CMD"
    echo ""
    echo "usage: lrt <cmd> [options]"
    echo ""
    echo "install: lrt i/install <rock name or rockspec> [additional luarocks arguments]"
    echo "run:     lrt r/run <command name> [arguments]"
    echo "clean:   lrt c/clean"
    exit 1
    ;;
esac
