#!/bin/bash

CMD=$1
shift

case $CMD in
  r | run)
    (eval $(luarocks path --bin --tree lua_modules); "$@")
    ;;

  i | install)
    luarocks install --tree lua_modules "$@"
    ;;

  c | clean)
    luarocks purge --tree lua_modules
    ;;

  *)
    echo "Unknown command $CMD"
    exit 1
    ;;
esac
